### ISSUE TITLE
valueChanged event fires twice when crossing the min or max threshold

### ISSUE THREAD

**Issue by techniq** [googlearchive/core-range#4]
The `valueChanged` event fires twice when crossing the min or max threshold (once for the value over/under the threshold, and again when the value is returned back to within range).  I would expect no valueChanged events to fire as the value shouldn't be able to cross the threshold(s)?

Example:

``` html
<html>
  <head>
    <title>core-range issue</title>
    <link rel="import" href="bower_components/core-range/core-range.html">
  </head>
  <body>
    <core-range-issue></core-range-issue>

    <polymer-element name="core-range-issue">
      <template>
        <core-range min="0" max="5" value="{{value}}"></core-range>
        <button on-tap="{{decrement}}">-</button> {{value}} <button on-tap="{{increment}}">+</button>
      </template>

      <script>
        Polymer({
          increment: function() {
            this.value += 1;
          },
          decrement: function() {
            this.value -= 1;
          },
          valueChanged: function(oldValue, newValue) {
            console.log('VALUE CHANGED', 'old:', oldValue, 'new:', newValue);
          }
        });
      </script>
    </polymer-element>
  </body>
</html>
```

Pressing the - button to decrement below 0 produces the following log output:

```
VALUE CHANGED old: 0 new: -1
VALUE CHANGED old: -1 new: 0 
```

Pressing the + button up to 5, and then again produces the following log output:

```
VALUE CHANGED old: 5 new: 6
VALUE CHANGED old: 6 new: 5 
```

**Comment by frankiefu** [comment]
`valueChanged` is a change handler on the property `value`.  When the value of `value` changes, `valueChanged` is invoked.  So what you are seeing is expected.  For example when pressing the - button to decrement below 0, value changes from 0 to -1 inside decrement(), that fires the `valueChanged`.  Then `core-range` gets the value and tries to adjust it from -1 to 0 and that fires another `valueChanged`.

**Comment by techniq** [comment]
It makes since because I'm passing in `value` that core-range is binding to and incrementing/decrementing that property.  I guess I was expecting core-range to somehow block/clamp the changing of the value and/or not fire a change event when it happens.  

I've modified my increment/decrement functions to not allow the value to go past it's thresholds (and thus not fire the change event which was causing an issue in my app as it fires a websocket message to multiple clients).  

``` js
Polymer({
  increment: function() {
      if (this.value < this.max) {
        this.value += 1;
      }
  },
  decrement: function() {
      if (this.value > this.min) {
        this.value -= 1;
      }
  },
  valueChanged: function(oldValue, newValue) {
    this.fire('change', this.value);
  }
});
```
